# This file was generated by GoReleaser. DO NOT EDIT.
class Getenvoy < Formula
  desc "Distribute, deploy and operate a fleet of Envoys"
  homepage "https://github.com/tetratelabs/getenvoy"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tetratelabs/getenvoy/releases/download/v0.2.0/getenvoy_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "f08438b83d3059862b50f2a91af6a38c2637433822c8fe2b6a12806d423f3087"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tetratelabs/getenvoy/releases/download/v0.2.0/getenvoy_0.2.0_Linux_x86_64.tar.gz"
      sha256 "afc8fc25d0619f8d07d3cc45fa606bdeae93ef450f90366d1aba08508699b258"
    end
  end

  def install
    bin.install "getenvoy"
  end

  test do
    system "#{bin}/getenvoy --help"
  end
end
