# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getenvoy < Formula
  desc "Install and run Envoy"
  homepage "https://github.com/tetratelabs/getenvoy"
  version "0.3.1"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tetratelabs/getenvoy/releases/download/v0.3.1/getenvoy_0.3.1_darwin_amd64.tar.gz"
      sha256 "769ca6e0a7e2628f5092016aebb70bae8ee69013d3f3027b82787c0041758970"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tetratelabs/getenvoy/releases/download/v0.3.1/getenvoy_0.3.1_darwin_arm64.tar.gz"
      sha256 "3955c290c5093d10a81fa57f78954500d2c80d001992f08e77aa778075a09009"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tetratelabs/getenvoy/releases/download/v0.3.1/getenvoy_0.3.1_linux_amd64.tar.gz"
      sha256 "3cc86e5d01e66692d5d7c6a704a91bca7ae4e8bfac5679fcbb843552c95a19e6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tetratelabs/getenvoy/releases/download/v0.3.1/getenvoy_0.3.1_linux_arm64.tar.gz"
      sha256 "5a8016b311bc6febd0cb8bfc1de9fea3cb5e5e71e844c9f9304e4dd6dba647c0"
    end
  end

  def install
    bin.install "getenvoy"
  end

  test do
    system "#{bin}/getenvoy -v"
  end
end
